export const GET_DASHBOARD = 'DASHBOARD_GET_DASHBOARD'
export const SET_DASHBOARD = 'DASHBOARD_SET_DASHBOARD'
export const GET_COLUMNS = 'DASHBOARD_GET_COLUMNS'
export const GET_TASKS = 'DASHBOARD_GET_TASKS'
