export const SAVE_TASK             = 'DASBOARD_TASK_EDITOR_SAVE_TASK'
export const UPDATE_SAVED_TASK     = 'DASBOARD_TASK_EDITOR_UPDATE_SAVED_TASK'

export const SET_TASK              = 'DASBOARD_TASK_EDITOR_SET_TASK'
export const UPDATE_TASK           = 'DASBOARD_TASK_EDITOR_UPDATE_TASK'
export const CLEAR_TASK            = 'DASBOARD_TASK_EDITOR_CLEAR_TASK'