export const SET_STATE = 'DASHBOARD_SET_STATE'
export const UPDATE_DASHBOARD = 'DASHBOARD_UPDATE_DASHBOARD'

export const SET_SECTIONS = 'DASHBOARD_SET_SECTIONS'
export const UPDATE_SECTIONS = 'DASHBOARD_UPDATE_SECTIONS'
export const DELETE_SECTIONS = 'DASHBOARD_DELETE_SECTIONS'
