export const SET_STATE = 'DASHBOARD_SET_STATE'
export const UPDATE_DASHBOARD = 'DASHBOARD_UPDATE_DASHBOARD'

export const SET_SECTIONS = 'DASHBOARD_SET_SECTIONS'

export const INIT_SECTION = 'DASHBOARD_INIT_SECTION'
export const CREATE_SECTION = 'DASHBOARD_CREATE_SECTION'
export const UPDATE_SECTION = 'DASHBOARD_UPDATE_SECTION'
export const REMOVE_SECTION = 'DASHBOARD_REMOVE_SECTION'
